# Generated by Selenium IDE
from testCreate import TestCreate
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support import expected_conditions as EC


class TestCreateLocal(TestCreate):
  def setup_method(self,endereco_arq, nome,pais,estado,cidade,nome_rua,numero,complemento):
    self.config()
    self.endereco_arq = endereco_arq
    self.nome= nome
    self.pais= pais
    self.estado=estado
    self.cidade=cidade
    self.nome_rua=nome_rua
    self.numero=numero #int
    self.complemento =complemento #int
  
  def execute_test(self):
    try:
      self.driver.get(self.endereco_arq)
      self.driver.set_window_size(1280, 937)
      self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(3)").click()
      self.driver.find_element(By.ID, "name").click()
      self.driver.find_element(By.ID, "name").send_keys(self.nome)
      self.driver.find_element(By.ID, "pais").click()
      self.driver.find_element(By.ID, "pais").send_keys(self.pais)
      self.driver.find_element(By.ID, "estado").click()
      self.driver.find_element(By.ID, "estado").send_keys(self.estado)
      self.driver.find_element(By.ID, "cidade").click()
      self.driver.find_element(By.ID, "cidade").send_keys(self.cidade)
      self.driver.find_element(By.ID, "rua").click()
      self.driver.find_element(By.ID, "rua").send_keys(self.nome_rua)
      self.driver.find_element(By.ID, "complemento").click()
      self.driver.find_element(By.ID, "numero").click()
      self.driver.find_element(By.ID, "numero").send_keys(str(self.numero))
      self.driver.find_element(By.ID, "complemento").click()
      self.driver.find_element(By.ID, "complemento").send_keys(str(self.complemento))
      self.driver.find_element(By.CSS_SELECTOR, "button").click()
      WebDriverWait(self.driver, 3).until(EC.alert_is_present())
      self.driver.switch_to.alert.accept()
      self.driver.find_element(By.CSS_SELECTOR, "h1").click()
      return True
    except:
      return False