# Generated by Selenium IDE
from testCreate import TestCreate

class TestCreateSediar(TestCreate):
  def setup_method(self, endereco,packId,placeId,eventId):
    self.config()
    self.endereco = endereco
    self.packId = packId
    self.placeId = placeId
    self.eventId = eventId
  
  def execute_test(self):
    self.driver.get(self.endereco)
    self.driver.set_window_size(1280, 937)
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(5)").click()
    self.driver.find_element(By.ID, "packId").click()
    self.driver.find_element(By.ID, "packId").send_keys(str(self.packId))
    self.driver.find_element(By.ID, "placeId").click()
    self.driver.find_element(By.ID, "placeId").send_keys(str(self.placeId))
    self.driver.find_element(By.ID, "eventId").click()
    self.driver.find_element(By.ID, "eventId").send_keys(str(self.eventId))
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
  
