# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEventsuccescreated():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_eventsuccescreated(self):
    self.driver.get("http://127.0.0.1:5500/public/mainPage/index.html")
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(2)").click()
    self.driver.find_element(By.ID, "Form").click()
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys("event name")
    dropdown = self.driver.find_element(By.ID, "tipo")
    dropdown.find_element(By.XPATH, "//option[. = 'música']").click()
    dropdown = self.driver.find_element(By.ID, "status")
    dropdown.find_element(By.XPATH, "//option[. = 'pendente']").click()
    self.driver.find_element(By.ID, "descricao").click()
    self.driver.find_element(By.ID, "descricao").send_keys("description")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()

  
